input {
  # От Beats (Filebeat, Auditbeat)
  beats {
    port => 5044
  }

  # Syslog (на будущее, для сетевого оборудования)
  syslog {
    port => 5140
    type => "syslog"
  }

  # JSON-логи приложений (на будущее)
  tcp {
    port => 5141
    codec => json_lines
    type => "app_json"
  }
}
