output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "********"
    ssl_enabled => true
    ssl_certificate_authorities => "/etc/logstash/elastic-ca.crt"
    index => "rsb-siem-%{+YYYY.MM.dd}"
  }

  # Для отладки можно временно включить:
  # stdout { codec => rubydebug }
}
